---
abstract: 'Queue Request Form for RTs FormTools'
author:
  - 'Torsten Brumm <tbrumm@mac.com>'
build_requires:
  ExtUtils::MakeMaker: 6.42
configure_requires:
  ExtUtils::MakeMaker: 6.42
distribution_type: module
generated_by: 'Module::Install version 0.92'
license: perl
meta-spec:
  url: http://module-build.sourceforge.net/META-spec-v1.4.html
  version: 1.4
name: RT-Extension-FormTools-QueueRequest
no_index:
  directory:
    - lib
    - html
    - inc
requires:
  perl: 5.8.3
resources:
  license: http://dev.perl.org/licenses/
version: 0.02
